error_log /dev/stderr info;
pid /tmp/nginx.pid;

events {}

http {
    access_log /dev/stdout;
    upstream smart_backends {
        server 127.0.0.1:50051;
        server 127.0.0.1:50052;
    }

    server {
        listen 8080 http2;

        location / {
            grpc_pass grpc://smart_backends;
        }
    }
}
